apiVersion: v1
data:
  SMTP_PASSWORD: ZXhhbXBsZQo=
  SMTP_SERVER: ZXhhbXBsZQo=
  SMTP_USERNAME: ZXhhbXBsZQo=
kind: Secret
metadata:
  name: mail.auth
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mail.config
data:
  SERVER_HOSTNAME: mail.example.com

